name: Build and Publish Wheels

on:
  push:
    tags:
      - "v*"  # Build & publish on version tags (e.g. v1.2.3)
  workflow_dispatch:  # Allow manual trigger

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Configure Poetry
        run: poetry config virtualenvs.create true && poetry lock

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Check C++ formatting
        run: |
          echo "Checking C++ code formatting..."
          poetry run clang-format --dry-run --Werror $(find src/ -name '*.cpp' -o -name '*.hpp')

      - name: Build package wheel
        run: |
          pip install cibuildwheel
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            cibuildwheel --output-dir dist --platform linux
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            CIBW_CONFIG_SETTINGS="setup-args=-Dmacos_arch=x86_64" cibuildwheel --output-dir dist --platform macos --archs x86_64
            CIBW_CONFIG_SETTINGS="setup-args=-Dmacos_arch=arm64" cibuildwheel --output-dir dist --platform macos --archs arm64
          fi
        env:
          MACOSX_DEPLOYMENT_TARGET: '15.0'
          CIBW_SKIP: "pp* *-musllinux* cp36-* cp37-* cp38-*"
          HOMEBREW_PREFIX: ""
          HOMEBREW_CELLAR: ""
          HOMEBREW_REPOSITORY: ""
          PKG_CONFIG_PATH: ""
          CIBW_ENVIRONMENT: "HOMEBREW_PREFIX='' HOMEBREW_CELLAR='' HOMEBREW_REPOSITORY='' PKG_CONFIG_PATH=''"

      - name: Upload built wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: dist/*.whl

  publish_testpypi:
    name: Publish to TestPyPI
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Upload to TestPyPI
        run: |
          pip install --upgrade pip poetry
          ls -lrth dist
          mkdir -p dist_flat
          cp dist/**/*.whl dist_flat/
          rm -rf dist
          mv dist_flat dist
          ls -lrth dist
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry publish -r testpypi -u __token__ -p ${{ secrets.TESTPYPI_API_TOKEN }}

  publish:
    name: Publish to PyPI
    needs: publish_testpypi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          path: dist

      - uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Upload to PyPI
        run: |
          pip install --upgrade pip poetry
          mkdir -p dist_flat
          cp dist/**/*.whl dist_flat/
          rm -rf dist
          mv dist_flat dist
          ls -lrth dist
          echo poetry publish -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
