name: Build and Install (Python Matrix)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: python-${{ matrix.python }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.9"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Configure Poetry
        run: poetry config virtualenvs.create true && poetry lock

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Check C++ formatting
        run: |
          echo "Checking C++ code formatting..."
          poetry run clang-format --dry-run --Werror $(find src/ -name '*.cpp' -o -name '*.hpp')

      - name: Build package wheel
        run: |
          poetry build

      - name: Patch RPATHs in wheel
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            pip install auditwheel
            auditwheel show dist/*.whl
            pwd
            auditwheel repair -w repaired_dist/ dist/*.whl
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            pip install delocate
            delocate-listdeps dist/*.whl
            pwd
            delocate-wheel -w repaired_dist/ dist/*.whl
          fi

      - name: Install package wheel
        run: |
          ls -lrth repaired_dist
          poetry run pip install repaired_dist/*.whl

      - name: Run tests
        run: |
          poetry run pytest --maxfail=1 --disable-warnings -q
